# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choice_panel.ui',
# licensing of 'choice_panel.ui' applies.
#
# Created: Mon Jul  5 01:24:51 2021
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_WDG_choice_panel(object):
    def setupUi(self, WDG_choice_panel):
        WDG_choice_panel.setObjectName("WDG_choice_panel")
        WDG_choice_panel.resize(481, 988)
        self.horizontalLayout = QtWidgets.QHBoxLayout(WDG_choice_panel)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(WDG_choice_panel)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 447, 1062))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frame_choice_panel = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_choice_panel.setAcceptDrops(True)
        self.frame_choice_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_choice_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_choice_panel.setObjectName("frame_choice_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_choice_panel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LBL_choice_panel = QtWidgets.QLabel(self.frame_choice_panel)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setWeight(75)
        font.setBold(True)
        self.LBL_choice_panel.setFont(font)
        self.LBL_choice_panel.setAcceptDrops(False)
        self.LBL_choice_panel.setObjectName("LBL_choice_panel")
        self.verticalLayout.addWidget(self.LBL_choice_panel)
        self.choice_panel_label_separator = QtWidgets.QFrame(self.frame_choice_panel)
        self.choice_panel_label_separator.setAcceptDrops(False)
        self.choice_panel_label_separator.setFrameShape(QtWidgets.QFrame.HLine)
        self.choice_panel_label_separator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.choice_panel_label_separator.setObjectName("choice_panel_label_separator")
        self.verticalLayout.addWidget(self.choice_panel_label_separator)
        self.LBL_select_station = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_select_station.setObjectName("LBL_select_station")
        self.verticalLayout.addWidget(self.LBL_select_station)
        self.CBX_select_station = QtWidgets.QComboBox(self.frame_choice_panel)
        self.CBX_select_station.setObjectName("CBX_select_station")
        self.CBX_select_station.addItem("")
        self.CBX_select_station.addItem("")
        self.CBX_select_station.addItem("")
        self.CBX_select_station.addItem("")
        self.verticalLayout.addWidget(self.CBX_select_station)
        self.LBL_cal_type = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_cal_type.setObjectName("LBL_cal_type")
        self.verticalLayout.addWidget(self.LBL_cal_type)
        self.CBX_select_cal_type = QtWidgets.QComboBox(self.frame_choice_panel)
        self.CBX_select_cal_type.setObjectName("CBX_select_cal_type")
        self.CBX_select_cal_type.addItem("")
        self.CBX_select_cal_type.addItem("")
        self.CBX_select_cal_type.addItem("")
        self.CBX_select_cal_type.addItem("")
        self.verticalLayout.addWidget(self.CBX_select_cal_type)
        self.choice_panel_label_separator_2 = QtWidgets.QFrame(self.frame_choice_panel)
        self.choice_panel_label_separator_2.setAcceptDrops(False)
        self.choice_panel_label_separator_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.choice_panel_label_separator_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.choice_panel_label_separator_2.setObjectName("choice_panel_label_separator_2")
        self.verticalLayout.addWidget(self.choice_panel_label_separator_2)
        self.LBL_general_params = QtWidgets.QLabel(self.frame_choice_panel)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setWeight(75)
        font.setBold(True)
        self.LBL_general_params.setFont(font)
        self.LBL_general_params.setAcceptDrops(False)
        self.LBL_general_params.setObjectName("LBL_general_params")
        self.verticalLayout.addWidget(self.LBL_general_params)
        self.LBL_velocity = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_velocity.setObjectName("LBL_velocity")
        self.verticalLayout.addWidget(self.LBL_velocity)
        self.LBL_velocity_2 = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_velocity_2.setObjectName("LBL_velocity_2")
        self.verticalLayout.addWidget(self.LBL_velocity_2)
        self.DSB_velocity = QtWidgets.QDoubleSpinBox(self.frame_choice_panel)
        self.DSB_velocity.setMinimum(0.0)
        self.DSB_velocity.setMaximum(1.0)
        self.DSB_velocity.setSingleStep(0.05)
        self.DSB_velocity.setObjectName("DSB_velocity")
        self.verticalLayout.addWidget(self.DSB_velocity)
        self.LBL_time_pout = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_time_pout.setObjectName("LBL_time_pout")
        self.verticalLayout.addWidget(self.LBL_time_pout)
        self.LBL_velocity_3 = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_velocity_3.setObjectName("LBL_velocity_3")
        self.verticalLayout.addWidget(self.LBL_velocity_3)
        self.DSB_time_out = QtWidgets.QDoubleSpinBox(self.frame_choice_panel)
        self.DSB_time_out.setMinimum(0.0)
        self.DSB_time_out.setMaximum(50.0)
        self.DSB_time_out.setObjectName("DSB_time_out")
        self.verticalLayout.addWidget(self.DSB_time_out)
        self.LBL_force = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_force.setObjectName("LBL_force")
        self.verticalLayout.addWidget(self.LBL_force)
        self.LBL_velocity_7 = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_velocity_7.setObjectName("LBL_velocity_7")
        self.verticalLayout.addWidget(self.LBL_velocity_7)
        self.DSB_force = QtWidgets.QDoubleSpinBox(self.frame_choice_panel)
        self.DSB_force.setMinimum(0.0)
        self.DSB_force.setMaximum(1.0)
        self.DSB_force.setSingleStep(0.05)
        self.DSB_force.setObjectName("DSB_force")
        self.verticalLayout.addWidget(self.DSB_force)
        self.LBL_move_type = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_move_type.setObjectName("LBL_move_type")
        self.verticalLayout.addWidget(self.LBL_move_type)
        self.LBL_velocity_8 = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_velocity_8.setObjectName("LBL_velocity_8")
        self.verticalLayout.addWidget(self.LBL_velocity_8)
        self.CBX_move_type = QtWidgets.QComboBox(self.frame_choice_panel)
        self.CBX_move_type.setObjectName("CBX_move_type")
        self.CBX_move_type.addItem("")
        self.CBX_move_type.addItem("")
        self.verticalLayout.addWidget(self.CBX_move_type)
        self.LBL_R = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_R.setObjectName("LBL_R")
        self.verticalLayout.addWidget(self.LBL_R)
        self.LBL_velocity_9 = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_velocity_9.setObjectName("LBL_velocity_9")
        self.verticalLayout.addWidget(self.LBL_velocity_9)
        self.DSB_Rx = QtWidgets.QDoubleSpinBox(self.frame_choice_panel)
        self.DSB_Rx.setDecimals(4)
        self.DSB_Rx.setMinimum(-7.0)
        self.DSB_Rx.setMaximum(7.0)
        self.DSB_Rx.setSingleStep(0.025)
        self.DSB_Rx.setObjectName("DSB_Rx")
        self.verticalLayout.addWidget(self.DSB_Rx)
        self.LBL_Ry = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_Ry.setObjectName("LBL_Ry")
        self.verticalLayout.addWidget(self.LBL_Ry)
        self.LBL_velocity_10 = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_velocity_10.setObjectName("LBL_velocity_10")
        self.verticalLayout.addWidget(self.LBL_velocity_10)
        self.DSB_Ry = QtWidgets.QDoubleSpinBox(self.frame_choice_panel)
        self.DSB_Ry.setDecimals(4)
        self.DSB_Ry.setMinimum(-7.0)
        self.DSB_Ry.setMaximum(7.0)
        self.DSB_Ry.setSingleStep(0.025)
        self.DSB_Ry.setObjectName("DSB_Ry")
        self.verticalLayout.addWidget(self.DSB_Ry)
        self.LBL_Rz = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_Rz.setObjectName("LBL_Rz")
        self.verticalLayout.addWidget(self.LBL_Rz)
        self.LBL_velocity_11 = QtWidgets.QLabel(self.frame_choice_panel)
        self.LBL_velocity_11.setObjectName("LBL_velocity_11")
        self.verticalLayout.addWidget(self.LBL_velocity_11)
        self.DSB_Rz = QtWidgets.QDoubleSpinBox(self.frame_choice_panel)
        self.DSB_Rz.setDecimals(4)
        self.DSB_Rz.setMinimum(-7.0)
        self.DSB_Rz.setMaximum(7.0)
        self.DSB_Rz.setSingleStep(0.025)
        self.DSB_Rz.setObjectName("DSB_Rz")
        self.verticalLayout.addWidget(self.DSB_Rz)
        self.general_params_label_separator = QtWidgets.QFrame(self.frame_choice_panel)
        self.general_params_label_separator.setAcceptDrops(False)
        self.general_params_label_separator.setFrameShape(QtWidgets.QFrame.HLine)
        self.general_params_label_separator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.general_params_label_separator.setObjectName("general_params_label_separator")
        self.verticalLayout.addWidget(self.general_params_label_separator)
        self.LBL_source_csv_path = QtWidgets.QLabel(self.frame_choice_panel)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setWeight(75)
        font.setBold(True)
        self.LBL_source_csv_path.setFont(font)
        self.LBL_source_csv_path.setAcceptDrops(False)
        self.LBL_source_csv_path.setObjectName("LBL_source_csv_path")
        self.verticalLayout.addWidget(self.LBL_source_csv_path)
        self.TXBX_src_path = QtWidgets.QLineEdit(self.frame_choice_panel)
        self.TXBX_src_path.setObjectName("TXBX_src_path")
        self.verticalLayout.addWidget(self.TXBX_src_path)
        self.PB_src_path = QtWidgets.QPushButton(self.frame_choice_panel)
        self.PB_src_path.setObjectName("PB_src_path")
        self.verticalLayout.addWidget(self.PB_src_path)
        self.LBL_dest_csv_path = QtWidgets.QLabel(self.frame_choice_panel)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setWeight(75)
        font.setBold(True)
        self.LBL_dest_csv_path.setFont(font)
        self.LBL_dest_csv_path.setAcceptDrops(False)
        self.LBL_dest_csv_path.setObjectName("LBL_dest_csv_path")
        self.verticalLayout.addWidget(self.LBL_dest_csv_path)
        self.TXBX_dest_path = QtWidgets.QLineEdit(self.frame_choice_panel)
        self.TXBX_dest_path.setObjectName("TXBX_dest_path")
        self.verticalLayout.addWidget(self.TXBX_dest_path)
        self.PB_dest_path = QtWidgets.QPushButton(self.frame_choice_panel)
        self.PB_dest_path.setObjectName("PB_dest_path")
        self.verticalLayout.addWidget(self.PB_dest_path)
        self.gridLayout.addWidget(self.frame_choice_panel, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(WDG_choice_panel)
        QtCore.QMetaObject.connectSlotsByName(WDG_choice_panel)

    def retranslateUi(self, WDG_choice_panel):
        WDG_choice_panel.setWindowTitle(QtWidgets.QApplication.translate("WDG_choice_panel", "Form", None, -1))
        self.LBL_choice_panel.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "                       CHOICE PANEL", None, -1))
        self.LBL_select_station.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Select station:", None, -1))
        self.CBX_select_station.setItemText(0, QtWidgets.QApplication.translate("WDG_choice_panel", "Station 1", None, -1))
        self.CBX_select_station.setItemText(1, QtWidgets.QApplication.translate("WDG_choice_panel", "Station 2", None, -1))
        self.CBX_select_station.setItemText(2, QtWidgets.QApplication.translate("WDG_choice_panel", "Station 3", None, -1))
        self.CBX_select_station.setItemText(3, QtWidgets.QApplication.translate("WDG_choice_panel", "Station 4", None, -1))
        self.LBL_cal_type.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Calibration Type:", None, -1))
        self.CBX_select_cal_type.setItemText(0, QtWidgets.QApplication.translate("WDG_choice_panel", "Pick basket", None, -1))
        self.CBX_select_cal_type.setItemText(1, QtWidgets.QApplication.translate("WDG_choice_panel", "Scanner", None, -1))
        self.CBX_select_cal_type.setItemText(2, QtWidgets.QApplication.translate("WDG_choice_panel", "Drop basket", None, -1))
        self.CBX_select_cal_type.setItemText(3, QtWidgets.QApplication.translate("WDG_choice_panel", "Table", None, -1))
        self.LBL_general_params.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "GENERAL PARAMETERS", None, -1))
        self.LBL_velocity.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Velocity:", None, -1))
        self.LBL_velocity_2.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Range: 0 to 1", None, -1))
        self.LBL_time_pout.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Time out:", None, -1))
        self.LBL_velocity_3.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Range: 0 to 50s", None, -1))
        self.LBL_force.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Force:", None, -1))
        self.LBL_velocity_7.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Range: 0 to 1", None, -1))
        self.LBL_move_type.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Motion type:", None, -1))
        self.LBL_velocity_8.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "L or J", None, -1))
        self.CBX_move_type.setItemText(0, QtWidgets.QApplication.translate("WDG_choice_panel", "Linear", None, -1))
        self.CBX_move_type.setItemText(1, QtWidgets.QApplication.translate("WDG_choice_panel", "Rotational", None, -1))
        self.LBL_R.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Rx:", None, -1))
        self.LBL_velocity_9.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "radians", None, -1))
        self.LBL_Ry.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Ry:", None, -1))
        self.LBL_velocity_10.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "radians", None, -1))
        self.LBL_Rz.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Rz:", None, -1))
        self.LBL_velocity_11.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "radians", None, -1))
        self.LBL_source_csv_path.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "SOURCE CSV PATH", None, -1))
        self.PB_src_path.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Browse", None, -1))
        self.LBL_dest_csv_path.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "DESTINATION CSV PATH", None, -1))
        self.PB_dest_path.setText(QtWidgets.QApplication.translate("WDG_choice_panel", "Browse", None, -1))

